/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Web.App;

import java.util.ArrayList;

import javax.sql.rowset.serial.SerialArray;

public class App {
    
    public boolean isTranspose(ArrayList<ArrayList<Integer>> userMatrix,Integer ... nums) {
        int counter = 0;

        for(Integer i : nums){
            counter ++;
        }

        int len = (int)Math.sqrt(counter);
        
        if((len*len) != counter)
            return false;

        ArrayList<ArrayList<Integer>> ownMatrix = new ArrayList<>();
        ownMatrix.add(new ArrayList<Integer>());

        int line = 0;
        int counterOfNums = 0;
        for(Integer i : nums) {
            
            if(counterOfNums == len){
                line++;
                counterOfNums = 0;
                ownMatrix.add(new ArrayList<Integer>());
            }

            ownMatrix.get(line).add(i);
            counterOfNums++;
        }

        if(userMatrix.size() != ownMatrix.size() || userMatrix.get(0).size() != ownMatrix.get(0).size())
            return false;
        

        for(int i = 0; i < len; i++){
            for(int j = 0; j < len;j++){
                if(userMatrix.get(i).get(j) != ownMatrix.get(j).get(i))
                    return false;
            }
        }
        
        return true;
    }
}
